### PR TITLE
BUG: Fix broken expansions for shell commands.

### PR DESCRIPTION
**Pull request by prabhuramachandran**

### CODE REVIEW

**Comment by jlstevens** [comment]
I'll look at this closer later on in the day, but I'll make one comment now. 

I *think* the original version was used because Python 3 did not always supporting ``callable``:

```diff
-            if isinstance(v, types.FunctionType):
+            if callable(v):
```

Anyway, as the Travis tests seem to be passing, I guess ``callable`` must have been back-ported and available for all Python 3 versions now.

**Comment by prabhuramachandran** [comment]
Hmm, good point, I think the right way to do it is 
```
if isinstance(v, collections.Callable):
```

Do you want me to change that?  

BTW, I may have misunderstood how expansions are to be used so I just went ahead and fixed it the way I understood it.

**Comment by jbednar** [comment]
I think checking for callable() is clearer, now that it works again (since Python 3.2).

**Comment by prabhuramachandran** [comment]
Can this be merged then?

**Comment by jlstevens** [comment]
Yes, I think so!

**Pull request merged**
